/********************************************************************
* /afs/slac.stanford.edu/u/br/manuelf/releases/Ntuple51/workdir/./babar_code/PlotsThesis/file8SPxk5.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /afs/slac.stanford.edu/u/br/manuelf/releases/Ntuple51/workdir/./babar_code/PlotsThesis/file8SPxk5.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablefile8SPxk5();
extern void G__cpp_setup_inheritancefile8SPxk5();
extern void G__cpp_setup_typetablefile8SPxk5();
extern void G__cpp_setup_memvarfile8SPxk5();
extern void G__cpp_setup_globalfile8SPxk5();
extern void G__cpp_setup_memfuncfile8SPxk5();
extern void G__cpp_setup_funcfile8SPxk5();
extern void G__set_cpp_environmentfile8SPxk5();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "/afs/slac.stanford.edu/u/br/manuelf/releases/Ntuple51/workdir/./babar_code/PlotsThesis/Fit_Chi2.C"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__file8SPxk5LN_TH1F;
extern G__linked_taginfo G__file8SPxk5LN_TH2F;
extern G__linked_taginfo G__file8SPxk5LN_TTree;
extern G__linked_taginfo G__file8SPxk5LN_TString;
extern G__linked_taginfo G__file8SPxk5LN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__file8SPxk5LN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__file8SPxk5LN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__file8SPxk5LN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__file8SPxk5LN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__file8SPxk5LN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__file8SPxk5LN_maplEstringcOstringcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOstringgRsPgRsPgR;
extern G__linked_taginfo G__file8SPxk5LN_setlEpairlERooAbsArgmUcORooAbsArgmUgRcOlesslEpairlERooAbsArgmUcORooAbsArgmUgRsPgRcOallocatorlEpairlERooAbsArgmUcORooAbsArgmUgRsPgRsPgR;
extern G__linked_taginfo G__file8SPxk5LN_dequelERooAbsCachemUcOallocatorlERooAbsCachemUgRsPgR;

/* STUB derived class for protected member access */
