// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /afs/slac.stanford.edu/u/br/manuelf/releases/Ntuple51/workdir/./babar_code/PlotsThesis/Fit_Chi2.C;

#endif
