//
// File generated by rootcint at Sat Nov 12 14:22:53 2011

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h"
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "fileEAiiiF.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TStreamerInfo.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TCollectionProxy.h"
#include "TIsAProxy.h"
// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

/********************************************************
* /afs/slac.stanford.edu/u/br/manuelf/releases/Ntuple51/workdir/./babar_code/Efficiency/fileEAiiiF.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablefileEAiiiF();

extern "C" void G__set_cpp_environmentfileEAiiiF() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/afs/slac.stanford.edu/u/br/manuelf/releases/Ntuple51/workdir/./babar_code/Efficiency/EffiRatios.C");
  G__cpp_reset_tagtablefileEAiiiF();
}
#include <new>
extern "C" int G__cpp_dllrevfileEAiiiF() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */
static int G__fileEAiiiF__0_313(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      {
         TString* pobj;
         TString xobj = round((double) G__double(libp->para[0]), (int) G__int(libp->para[1])
, (double) G__double(libp->para[2]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
      break;
   case 2:
      {
         TString* pobj;
         TString xobj = round((double) G__double(libp->para[0]), (int) G__int(libp->para[1]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__fileEAiiiF__0_314(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      EffiRatios(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (int) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      EffiRatios(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      EffiRatios(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      EffiRatios();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncfileEAiiiF {
 public:
  G__Sizep2memfuncfileEAiiiF() {p=&G__Sizep2memfuncfileEAiiiF::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncfileEAiiiF::*p)();
};

size_t G__get_sizep2memfuncfileEAiiiF()
{
  G__Sizep2memfuncfileEAiiiF a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancefileEAiiiF() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablefileEAiiiF() {

   /* Setting up typedef entry */
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__fileEAiiiFLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__fileEAiiiFLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileEAiiiFLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__fileEAiiiFLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__fileEAiiiFLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,Version_t>",117,G__get_linked_tagnum(&G__fileEAiiiFLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,short>",117,G__get_linked_tagnum(&G__fileEAiiiFLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("multimap<void*,short,less<void*>>",117,G__get_linked_tagnum(&G__fileEAiiiFLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvarfileEAiiiF() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncfileEAiiiF() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalfileEAiiiF() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
   G__memfunc_setup("round", 552, G__fileEAiiiF__0_313, 117, G__get_linked_tagnum(&G__fileEAiiiFLN_TString), -1, 0, 3, 1, 1, 0, 
"d - - 0 - n i - - 0 - e "
"d - - 0 1. d", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EffiRatios", 1004, G__fileEAiiiF__0_314, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 \"\" base u 'TString' - 0 \"All\" Runs "
"i - - 0 0 doW", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcfileEAiiiF() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__fileEAiiiFLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__fileEAiiiFLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__fileEAiiiFLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__fileEAiiiFLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR = { "multimap<void*,short,less<void*>,allocator<pair<void* const,short> > >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablefileEAiiiF() {
  G__fileEAiiiFLN_TString.tagnum = -1 ;
  G__fileEAiiiFLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__fileEAiiiFLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__fileEAiiiFLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablefileEAiiiF() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum(&G__fileEAiiiFLN_TString);
   G__get_linked_tagnum(&G__fileEAiiiFLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum(&G__fileEAiiiFLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum(&G__fileEAiiiFLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR);
}
extern "C" void G__cpp_setupfileEAiiiF(void) {
  G__check_setup_version(30051515,"G__cpp_setupfileEAiiiF()");
  G__set_cpp_environmentfileEAiiiF();
  G__cpp_setup_tagtablefileEAiiiF();

  G__cpp_setup_inheritancefileEAiiiF();

  G__cpp_setup_typetablefileEAiiiF();

  G__cpp_setup_memvarfileEAiiiF();

  G__cpp_setup_memfuncfileEAiiiF();
  G__cpp_setup_globalfileEAiiiF();
  G__cpp_setup_funcfileEAiiiF();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncfileEAiiiF();
  return;
}
class G__cpp_setup_initfileEAiiiF {
  public:
    G__cpp_setup_initfileEAiiiF() { G__add_setup_func("fileEAiiiF",(G__incsetup)(&G__cpp_setupfileEAiiiF)); G__call_setup_funcs(); }
   ~G__cpp_setup_initfileEAiiiF() { G__remove_setup_func("fileEAiiiF"); }
};
G__cpp_setup_initfileEAiiiF G__cpp_setup_initializerfileEAiiiF;

