/********************************************************************
* /afs/slac.stanford.edu/u/br/manuelf/releases/Ntuple51/workdir/./babar_code/Efficiency/fileEAiiiF.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /afs/slac.stanford.edu/u/br/manuelf/releases/Ntuple51/workdir/./babar_code/Efficiency/fileEAiiiF.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablefileEAiiiF();
extern void G__cpp_setup_inheritancefileEAiiiF();
extern void G__cpp_setup_typetablefileEAiiiF();
extern void G__cpp_setup_memvarfileEAiiiF();
extern void G__cpp_setup_globalfileEAiiiF();
extern void G__cpp_setup_memfuncfileEAiiiF();
extern void G__cpp_setup_funcfileEAiiiF();
extern void G__set_cpp_environmentfileEAiiiF();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "/afs/slac.stanford.edu/u/br/manuelf/releases/Ntuple51/workdir/./babar_code/Efficiency/EffiRatios.C"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__fileEAiiiFLN_TString;
extern G__linked_taginfo G__fileEAiiiFLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__fileEAiiiFLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fileEAiiiFLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;

/* STUB derived class for protected member access */
