double round(double d);

void TableDavid(TString tag="",TString isAdd = ""){
  // Cuts not yet done candExtraTracks==0&&candThetaLep>.4&&candThetaLep<2.6&&candM2>-4&&candM2<12&&candPstarLep>0&&candPstarLep<2.4
  TCut MMiss = "candPMiss>.2";
  TCut Q2 = "candQ2>4";
  TCut fit = "candFitProb>-.001";
  TCut mes = "candMES>5.27";
  TCut ee1 = "candType<3&&candEExtra<.2";
  TCut ee2 = "candType==3&&candEExtra<.15";
  TCut ee3 = "candType==4&&candEExtra<.3";
  TCut ee = (ee1||ee2||ee3);
  TCut kin1 = "(candType==1||candType==3)&&candPstarLep<2.31";
  TCut kin2 = "(candType==2||candType==4)&&candPstarLep<2.26";
  TCut kin = (kin1||kin2);
  TCut cleanD0 = "(candType<3||(candType==4&&candDstarType==1)) && (candDType<5||candDType==7||candDType==9)";
  TCut cleanDplus = "(candType==3||(candType==4&&candDstarType==2)) && (candDType<4||candDType>5)";
  TCut clean = (cleanD0 || cleanDplus);
  TCut basic= MMiss+Q2+ee;
  if(tag=="All")
    basic = MMiss+Q2+ee;
  else if(tag=="afterBestB")
    basic = fit;
  else if(tag=="EExtra")
    basic = ee;
  else if(tag=="MMiss")
    basic = MMiss;
  else if(tag=="Q2")
    basic = Q2;
  else if(tag=="Clean")
    basic = clean+MMiss+Q2+ee;

  // Loading files
  TChain ch("ntp1");
  if(isAdd==""){
    ch.Add("AWG82/ntuples/SP-1235-BSemiExcl-Run2-R22d-v06/*");
    ch.Add("AWG82/ntuples/SP-1235-BSemiExcl-Run4-R22d-v06/*");
    ch.Add("AWG82/ntuples/SP-1237-BSemiExcl-Run2-R22d-v06/*");
    ch.Add("AWG82/ntuples/SP-1237-BSemiExcl-Run4-R22d-v06/*");
  } else {
    ch.Add("AWG82/ntuples/SP-1235-BSemiExclAdd-Run2-R22f-v01/*");
    ch.Add("AWG82/ntuples/SP-1235-BSemiExclAdd-Run4-R22f-v01/*");
    ch.Add("AWG82/ntuples/SP-1237-BSemiExclAdd-Run2-R22f-v01/*");
    ch.Add("AWG82/ntuples/SP-1237-BSemiExclAdd-Run4-R22f-v01/*");
  }
  if(tag != "") tag = "_" + tag;
  fstream Table;
  Table.open("mycode/tables/table"+isAdd+tag+".txt",fstream::out);
  fstream tex;
  tex.open("mycode/tables/textable"+isAdd+tag+".txt",fstream::out);

  Table<<" D*0\tMazur22\t David\t  M/D\t R22/R14"<<endl;
  Table<<"=========================================="<<endl;
  tex<<"\\begin{tabular}{|l||cc|cc|}"<<endl<<"\\hline"<<endl;
  tex<<"$\\mathbf{D^{*0}}$ & R22_{Mazur} & R22_{David} & M/D & R22/R14 \\\\"<<endl;
  tex<<"\\hline \\hline"<<endl;
  int DYields[] = {133,2848,8,99,104,69};
  int MYields[] = {131,2798,16,72,97,79};
  Table<<"D*0 Tau";
  TCut cuts = basic+"MCType==6&&candType==2";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[0]<<"\t  "<<round((double)entries/(double)DYields[0]);
  Table<<"\t   "<<round((double)entries/(double)MYields[0]*711./535.)<<endl;
  tex<<"D^{*0} \\,\\tau \\,\\nu & "<<entries<<" & "<<DYields[0]<<" & "<<round((double)entries/(double)DYields[0]);
  tex<<" & "<<round((double)entries/(double)MYields[0]*711./535.)<<" \\\\"<<endl;
  Table<<"D*0 l";
  cuts = basic+"(MCType==2||MCType==4)&&candType==2";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[1]<<"\t  "<<round((double)entries/(double)DYields[1]);
  Table<<"\t   "<<round((double)entries/(double)MYields[1]*711./535.)<<endl;
  tex<<"D^{*0} \\,l \\,\\nu & "<<entries<<" & "<<DYields[1]<<" & "<<round((double)entries/(double)DYields[1]);
  tex<<" & "<<round((double)entries/(double)MYields[1]*711./535.)<<" \\\\"<<endl;
  Table<<"D0 Tau";
  cuts = basic+"MCType==5&&candType==2";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[2]<<"\t  "<<round((double)entries/(double)DYields[2]);
  Table<<"\t   "<<round((double)entries/(double)MYields[2]*711./535.)<<endl;
  tex<<"D^{0} \\,\\tau \\,\\nu & "<<entries<<" & "<<DYields[2]<<" & "<<round((double)entries/(double)DYields[2]);
  tex<<" & "<<round((double)entries/(double)MYields[2]*711./535.)<<" \\\\"<<endl;
  Table<<"D0 l";
  cuts = basic+"(MCType==1||MCType==3)&&candType==2";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[3]<<"\t  "<<round((double)entries/(double)DYields[3]);
  Table<<"\t   "<<round((double)entries/(double)MYields[3]*711./535.)<<endl;
  tex<<"D^{0} \\,l \\,\\nu & "<<entries<<" & "<<DYields[3]<<" & "<<round((double)entries/(double)DYields[3]);
  tex<<" & "<<round((double)entries/(double)MYields[3]*711./535.)<<" \\\\"<<endl;
  Table<<"D** l";
  cuts = basic+"(MCType==13||MCType==14)&&candType==2";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[4]<<"\t  "<<round((double)entries/(double)DYields[4]);
  Table<<"\t   "<<round((double)entries/(double)MYields[4]*711./535.)<<endl;
  tex<<"D^{**} \\,l \\,\\nu & "<<entries<<" & "<<DYields[4]<<" & "<<round((double)entries/(double)DYields[4]);
  tex<<" & "<<round((double)entries/(double)MYields[4]*711./535.)<<" \\\\"<<endl;
  Table<<"Bkg";
  cuts = basic+"(MCType==0||(MCType>6&&MCType<13))&&candType==2";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[5]<<"\t  "<<round((double)entries/(double)DYields[5]);
  Table<<"\t   "<<round((double)entries/(double)MYields[5]*711./535.)<<endl;
  tex<<"Bkg & "<<entries<<" & "<<DYields[5]<<" & "<<round((double)entries/(double)DYields[5]);
  tex<<" & "<<round((double)entries/(double)MYields[5]*711./535.)<<" \\\\"<<endl;
  tex<<"\\hline \\end{tabular}"<<endl<<endl;
  
  Table<<endl<<endl<<" D0\tMazur22\t David\t  M/D\t R22/R14"<<endl;
  Table<<"=========================================="<<endl;
  tex<<"\\begin{tabular}{|l||cc|cc|}"<<endl<<"\\hline"<<endl;
  tex<<"$\\mathbf{D^{0}}$ & R22_{Mazur} & R22_{David} & M/D & R22/R14 \\\\"<<endl;
  tex<<"\\hline \\hline"<<endl;
  int DYields[] = {110,155,1186,3875,346,163};
  int MYields[] = {142,153,1143,3010,270,187};
  Table<<"D0 Tau";
  cuts = basic+"MCType==5&&candType==1";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[0]<<"\t  "<<round((double)entries/(double)DYields[0]);
  Table<<"\t   "<<round((double)entries/(double)MYields[0]*711./535.)<<endl;
  tex<<"D^{0} \\,\\tau \\,\\nu & "<<entries<<" & "<<DYields[0]<<" & "<<round((double)entries/(double)DYields[0]);
  tex<<" & "<<round((double)entries/(double)MYields[0]*711./535.)<<" \\\\"<<endl;
  Table<<"D*0 Tau";
  TCut cuts = basic+"MCType==6&&candType==1";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[1]<<"\t  "<<round((double)entries/(double)DYields[1]);
  Table<<"\t   "<<round((double)entries/(double)MYields[1]*711./535.)<<endl;
  tex<<"D^{*0} \\,\\tau \\,\\nu & "<<entries<<" & "<<DYields[1]<<" & "<<round((double)entries/(double)DYields[1]);
  tex<<" & "<<round((double)entries/(double)MYields[1]*711./535.)<<" \\\\"<<endl;
  Table<<"D0 l";
  cuts = basic+"(MCType==1||MCType==3)&&candType==1";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[2]<<"\t  "<<round((double)entries/(double)DYields[2]);
  Table<<"\t   "<<round((double)entries/(double)MYields[2]*711./535.)<<endl;
  tex<<"D^{0} \\,l \\,\\nu & "<<entries<<" & "<<DYields[2]<<" & "<<round((double)entries/(double)DYields[2]);
  tex<<" & "<<round((double)entries/(double)MYields[2]*711./535.)<<" \\\\"<<endl;
  Table<<"D*0 l";
  cuts = basic+"(MCType==2||MCType==4)&&candType==1";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[3]<<"\t  "<<round((double)entries/(double)DYields[3]);
  Table<<"\t   "<<round((double)entries/(double)MYields[3]*711./535.)<<endl;
  tex<<"D^{*0} \\,l \\,\\nu & "<<entries<<" & "<<DYields[3]<<" & "<<round((double)entries/(double)DYields[3]);
  tex<<" & "<<round((double)entries/(double)MYields[3]*711./535.)<<" \\\\"<<endl;
  Table<<"D** l";
  cuts = basic+"(MCType==13||MCType==14)&&candType==1";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[4]<<"\t  "<<round((double)entries/(double)DYields[4]);
  Table<<"\t   "<<round((double)entries/(double)MYields[4]*711./535.)<<endl;
  tex<<"D^{**} \\,l \\,\\nu & "<<entries<<" & "<<DYields[4]<<" & "<<round((double)entries/(double)DYields[4]);
  tex<<" & "<<round((double)entries/(double)MYields[4]*711./535.)<<" \\\\"<<endl;
  Table<<"Bkg";
  cuts = basic+"(MCType==0||(MCType>6&&MCType<13))&&candType==1";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[5]<<"\t  "<<round((double)entries/(double)DYields[5]);
  Table<<"\t   "<<round((double)entries/(double)MYields[5]*711./535.)<<endl;
  tex<<"Bkg & "<<entries<<" & "<<DYields[5]<<" & "<<round((double)entries/(double)DYields[5]);
  tex<<" & "<<round((double)entries/(double)MYields[5]*711./535.)<<" \\\\"<<endl;
  tex<<"\\hline \\end{tabular}"<<endl<<endl;

  Table<<endl<<endl<<" D*+\tMazur22\t David\t  M/D\t R22/R14"<<endl;
  Table<<"=========================================="<<endl;
  tex<<"\\begin{tabular}{|l||cc|cc|}"<<endl<<"\\hline"<<endl;
  tex<<"$\\mathbf{D^{*+}}$ & R22_{Mazur} & R22_{David} & M/D & R22/R14 \\\\"<<endl;
  tex<<"\\hline \\hline"<<endl;
  int DYields[] = {87,1866,1,9,92,65};
  int MYields[] = {92,1695,4,5,50,29};
  Table<<"D*+ Tau";
  TCut cuts = basic+"MCType==12&&candType==4";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[0]<<"\t  "<<round((double)entries/(double)DYields[0]);
  Table<<"\t   "<<round((double)entries/(double)MYields[0]*711./535.)<<endl;
  tex<<"D^{*+} \\,\\tau \\,\\nu & "<<entries<<" & "<<DYields[0]<<" & "<<round((double)entries/(double)DYields[0]);
  tex<<" & "<<round((double)entries/(double)MYields[0]*711./535.)<<" \\\\"<<endl;
  Table<<"D*+ l";
  cuts = basic+"(MCType==8||MCType==10)&&candType==4";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[1]<<"\t  "<<round((double)entries/(double)DYields[1]);
  Table<<"\t   "<<round((double)entries/(double)MYields[1]*711./535.)<<endl;
  tex<<"D^{*+} \\,l \\,\\nu & "<<entries<<" & "<<DYields[1]<<" & "<<round((double)entries/(double)DYields[1]);
  tex<<" & "<<round((double)entries/(double)MYields[1]*711./535.)<<" \\\\"<<endl;
  Table<<"D+ Tau";
  cuts = basic+"MCType==11&&candType==4";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[2]<<"\t  "<<round((double)entries/(double)DYields[2]);
  Table<<"\t   "<<round((double)entries/(double)MYields[2]*711./535.)<<endl;
  tex<<"D^{+} \\,\\tau \\,\\nu & "<<entries<<" & "<<DYields[2]<<" & "<<round((double)entries/(double)DYields[2]);
  tex<<" & "<<round((double)entries/(double)MYields[2]*711./535.)<<" \\\\"<<endl;
  Table<<"D+ l";
  cuts = basic+"(MCType==7||MCType==9)&&candType==4";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[3]<<"\t  "<<round((double)entries/(double)DYields[3]);
  Table<<"\t   "<<round((double)entries/(double)MYields[3]*711./535.)<<endl;
  tex<<"D^{+} \\,l \\,\\nu & "<<entries<<" & "<<DYields[3]<<" & "<<round((double)entries/(double)DYields[3]);
  tex<<" & "<<round((double)entries/(double)MYields[3]*711./535.)<<" \\\\"<<endl;
  Table<<"D** l";
  cuts = basic+"(MCType==13||MCType==14)&&candType==4";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[4]<<"\t  "<<round((double)entries/(double)DYields[4]);
  Table<<"\t   "<<round((double)entries/(double)MYields[4]*711./535.)<<endl;
  tex<<"D^{**} \\,l \\,\\nu & "<<entries<<" & "<<DYields[4]<<" & "<<round((double)entries/(double)DYields[4]);
  tex<<" & "<<round((double)entries/(double)MYields[4]*711./535.)<<" \\\\"<<endl;
  Table<<"Bkg";
  cuts = basic+"(MCType>=0&&MCType<7)&&candType==4";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[5]<<"\t  "<<round((double)entries/(double)DYields[5]);
  Table<<"\t   "<<round((double)entries/(double)MYields[5]*711./535.)<<endl;
  tex<<"Bkg & "<<entries<<" & "<<DYields[5]<<" & "<<round((double)entries/(double)DYields[5]);
  tex<<" & "<<round((double)entries/(double)MYields[5]*711./535.)<<" \\\\"<<endl;
  tex<<"\\hline \\end{tabular}"<<endl<<endl;

  Table<<endl<<endl<<" D+\tMazur22\t David\t  M/D\t R22/R14"<<endl;
  Table<<"=========================================="<<endl;
  tex<<"\\begin{tabular}{|l||cc|cc|}"<<endl<<"\\hline"<<endl;
  tex<<"$\\mathbf{D^{+}}$ & R22_{Mazur} & R22_{David} & M/D & R22/R14 \\\\"<<endl;
  tex<<"\\hline \\hline"<<endl;
  int DYields[] = {46,14,401,448,93,63};
  int MYields[] = {43,22,427,380,34,40};
  Table<<"D+ Tau";
  cuts = basic+"MCType==11&&candType==3";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[0]<<"\t  "<<round((double)entries/(double)DYields[0]);
  Table<<"\t   "<<round((double)entries/(double)MYields[0]*711./535.)<<endl;
  tex<<"D^{+} \\,\\tau \\,\\nu & "<<entries<<" & "<<DYields[0]<<" & "<<round((double)entries/(double)DYields[0]);
  tex<<" & "<<round((double)entries/(double)MYields[0]*711./535.)<<" \\\\"<<endl;
  Table<<"D*+ Tau";
  TCut cuts = basic+"MCType==12&&candType==3";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[1]<<"\t  "<<round((double)entries/(double)DYields[1]);
  Table<<"\t   "<<round((double)entries/(double)MYields[1]*711./535.)<<endl;
  tex<<"D^{*+} \\,\\tau \\,\\nu & "<<entries<<" & "<<DYields[1]<<" & "<<round((double)entries/(double)DYields[1]);
  tex<<" & "<<round((double)entries/(double)MYields[1]*711./535.)<<" \\\\"<<endl;
  Table<<"D+ l";
  cuts = basic+"(MCType==7||MCType==9)&&candType==3";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[2]<<"\t  "<<round((double)entries/(double)DYields[2]);
  Table<<"\t   "<<round((double)entries/(double)MYields[2]*711./535.)<<endl;
  tex<<"D^{+} \\,l \\,\\nu & "<<entries<<" & "<<DYields[2]<<" & "<<round((double)entries/(double)DYields[2]);
  tex<<" & "<<round((double)entries/(double)MYields[2]*711./535.)<<" \\\\"<<endl;
  Table<<"D*+ l";
  cuts = basic+"(MCType==8||MCType==10)&&candType==3";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[3]<<"\t  "<<round((double)entries/(double)DYields[3]);
  Table<<"\t   "<<round((double)entries/(double)MYields[3]*711./535.)<<endl;
  tex<<"D^{*+} \\,l \\,\\nu & "<<entries<<" & "<<DYields[3]<<" & "<<round((double)entries/(double)DYields[3]);
  tex<<" & "<<round((double)entries/(double)MYields[3]*711./535.)<<" \\\\"<<endl;
  Table<<"D** l";
  cuts = basic+"(MCType==13||MCType==14)&&candType==3";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[4]<<"\t  "<<round((double)entries/(double)DYields[4]);
  Table<<"\t   "<<round((double)entries/(double)MYields[4]*711./535.)<<endl;
  tex<<"D^{**} \\,l \\,\\nu & "<<entries<<" & "<<DYields[4]<<" & "<<round((double)entries/(double)DYields[4]);
  tex<<" & "<<round((double)entries/(double)MYields[4]*711./535.)<<" \\\\"<<endl;
  Table<<"Bkg";
  cuts = basic+"(MCType>=0&&MCType<7)&&candType==3";
  int entries = ch.Draw("MCType",cuts);
  Table<<"\t  "<<entries<<"\t "<<DYields[5]<<"\t  "<<round((double)entries/(double)DYields[5]);
  Table<<"\t   "<<round((double)entries/(double)MYields[5]*711./535.)<<endl;
  tex<<"Bkg & "<<entries<<" & "<<DYields[5]<<" & "<<round((double)entries/(double)DYields[5]);
  tex<<" & "<<round((double)entries/(double)MYields[5]*711./535.)<<" \\\\"<<endl;
  tex<<"\\hline \\end{tabular}"<<endl<<endl;

}

double round(double d){
  double b = (int)(d *100+.5);
  return b/100;
}

